spring:
  application:
    name: employee
  datasource:
    url: jdbc:postgresql://postgres:5432/employee
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/db/changelog/db.master-changelog.xml

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    prometheus:
      enabled: true
    health:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true